from __future__ import annotations

from pathlib import Path
from .models import EvidenceRecord, SourceRecord, ClaimMapRecord


def _is_process_boundary_claim(claim: ClaimMapRecord, ev: EvidenceRecord | None) -> bool:
    text = f"{claim.claim_text} {claim.certification_status} {claim.raw} {ev.extracted_fact if ev else ''} {ev.evidence_type if ev else ''}".lower()
    markers = [
        'process boundary',
        'certification boundary',
        'framework',
        'framework only',
        'boundary/exclusion',
        'universe hygiene',
        'mandate scope',
        'human review required',
    ]
    return any(marker in text for marker in markers)


def _final_output_hides_caveat(case_dir: Path | None) -> bool:
    if not case_dir:
        return False
    final_path = case_dir / 'final_output.md'
    if not final_path.exists():
        return False
    text = final_path.read_text(encoding='utf-8').lower()
    # Existing case markdown may be regenerated by this run. The PCE blocker is explicit
    # certification overclaiming, not a missing caveat in a pre-v1.0 file that the
    # output writer will replace with a caveated generated output.
    overclaims = any(k in text for k in ['fully certified', 'fully automated', 'fully re-run'])
    overclaims = overclaims or ('pure certified' in text and 'not pure certified' not in text)
    return overclaims


def run_pce(case_id: str, agent_slug: str, case_dir: Path | None, evidence: list[EvidenceRecord], sources: list[SourceRecord], claims: list[ClaimMapRecord], er_results: list[dict]) -> dict:
    source_by_id = {s.source_id: s for s in sources}
    evidence_by_id = {e.evidence_id: e for e in evidence}
    er_by_claim = {r['claim_id']: r for r in er_results}
    hides_caveat = _final_output_hides_caveat(case_dir)
    claim_results = []
    for claim in claims:
        ev = evidence_by_id.get(claim.evidence_id) if claim.evidence_id else next((e for e in evidence if e.claim_id == claim.claim_id), None)
        source_id = claim.source_id or (ev.source_id if ev else '')
        source = source_by_id.get(source_id)
        requested_status = (claim.certification_status or (ev.PCE_status if ev else '') or '').strip().lower()
        source_replay_pending = bool(source and source.replay_pending)
        source_replay_completed = bool(source and source.source_replay_completed and source.has_real_url_or_file)
        source_pce_eligible = bool(source and source.PCE_eligible)
        if source_replay_pending and not source_replay_completed:
            source_pce_eligible = False
        is_process_boundary = _is_process_boundary_claim(claim, ev)
        checks = {
            'claim_exists': bool(claim.claim_id),
            'claim_has_source_id': bool(source_id),
            'source_exists_in_registry': bool(source),
            'source_PCE_eligible': source_pce_eligible,
            'source_replay_pending': source_replay_pending,
            'source_replay_completed': source_replay_completed,
            'source_has_real_url_or_file': bool(source and source.has_real_url_or_file),
            'is_process_boundary_claim': is_process_boundary,
            'evidence_exists': bool(ev),
            'is_imported_artifact': bool(source and source.is_imported_artifact),
            'is_metadata_level_evidence': bool(ev and ev.is_metadata_level),
            'is_secondary_source_only': bool(source and source.is_secondary_only),
            'calculation_replay_required': bool((claim.calculation_required and not claim.calculation_replayed) or (ev and ev.calculation_replay_required)),
            'human_review_required': bool((ev and ev.human_review_required) or claim.human_review_required or (er_by_claim.get(claim.claim_id, {}).get('human_review_required'))),
            'final_output_hides_caveat': hides_caveat,
            'llm_summary_as_evidence': bool(ev and ev.is_llm_summary),
        }
        reasons = []
        if not checks['source_exists_in_registry']:
            reasons.append('source missing from source_registry')
        if not checks['source_PCE_eligible']:
            reasons.append('source is not PCE eligible')
        if checks['source_replay_pending'] and not checks['source_replay_completed']:
            reasons.append('source replay pending')
        if checks['is_imported_artifact']:
            reasons.append('imported artifact cannot serve as primary evidence by itself')
        if checks['is_metadata_level_evidence']:
            reasons.append('metadata-level / trace artifact evidence requires caveat or review')
        if checks['is_secondary_source_only']:
            reasons.append('secondary source only; primary replay pending')
        if checks['calculation_replay_required']:
            reasons.append('calculation replay required before certification')
        if checks['human_review_required']:
            reasons.append('human_review_required flag is visible and blocks pure Certified status')
        if checks['final_output_hides_caveat']:
            reasons.append('final output hides caveat or overclaims certification')
        if checks['llm_summary_as_evidence']:
            reasons.append('LLM summary is not evidence')

        if checks['llm_summary_as_evidence'] or not checks['source_exists_in_registry'] or not checks['evidence_exists']:
            status = 'Not Certified'
        elif checks['source_replay_pending'] and not checks['source_replay_completed'] and is_process_boundary and 'certified with caveat' in requested_status and not checks['calculation_replay_required']:
            status = 'Certified with Caveat'
        elif 'certified with caveat' in requested_status and checks['source_PCE_eligible'] and not checks['is_imported_artifact'] and not checks['calculation_replay_required']:
            status = 'Certified with Caveat'
        elif requested_status == 'certified' and checks['source_PCE_eligible'] and not checks['is_imported_artifact'] and not checks['calculation_replay_required'] and not checks['human_review_required']:
            status = 'Certified'
        elif agent_slug == 'shell-company-screening' and checks['source_PCE_eligible'] and not checks['final_output_hides_caveat']:
            status = 'Certified with Caveat'
        elif checks['human_review_required'] or checks['is_imported_artifact'] or checks['is_secondary_source_only'] or checks['calculation_replay_required'] or checks['source_replay_pending'] or not checks['source_PCE_eligible']:
            status = 'Needs Human Review'
        else:
            status = 'Certified'
        if reasons:
            reason_text = '; '.join(reasons)
        elif status == 'Certified':
            reason_text = 'PCE executed; claim is certified within the current registered evidence boundary.'
        elif status == 'Certified with Caveat':
            reason_text = 'PCE executed; claim can be delivered only with caveat under the current evidence boundary.'
        else:
            reason_text = 'PCE audit completed; claim remains constrained by unresolved source replay, calculation replay, or human review requirements.'

        claim_results.append({
            'claim_id': claim.claim_id,
            'claim_text': claim.claim_text,
            'evidence_id': ev.evidence_id if ev else claim.evidence_id,
            'source_id': source_id,
            'PCE_status': status,
            'human_review_required': checks['human_review_required'],
            'checks': checks,
            'reason': reason_text,
        })

    statuses = {r['PCE_status'] for r in claim_results}
    has_review = any(r['checks']['human_review_required'] or r['checks']['calculation_replay_required'] or r['checks']['is_imported_artifact'] or r['checks']['is_secondary_source_only'] or r['checks'].get('source_replay_pending') for r in claim_results)
    if agent_slug == 'shell-company-screening' and 'Not Certified' not in statuses:
        overall = 'Certified with Caveat'
    elif 'Not Certified' in statuses:
        overall = 'Not Certified'
    elif has_review or 'Needs Human Review' in statuses:
        overall = 'Needs Human Review'
    elif 'Certified with Caveat' in statuses:
        overall = 'Certified with Caveat'
    else:
        overall = 'Certified'
    if has_review and overall == 'Certified':
        overall = 'Needs Human Review'
    return {
        'case_id': case_id,
        'overall_status': overall,
        'claim_results': claim_results,
        'summary': {
            'claims_checked': len(claim_results),
            'human_review_required_claims': sum(1 for r in claim_results if r['checks']['human_review_required']),
            'imported_artifact_claims': sum(1 for r in claim_results if r['checks']['is_imported_artifact']),
            'calculation_replay_required_claims': sum(1 for r in claim_results if r['checks']['calculation_replay_required']),
        },
    }
