from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path

from .pce.certification_report import certify_example
from .run_context import RunContext
from .trace.calculation_replay import replay_trace_calculations

REQUIRED_TRACE = [
    'candidate_universe_table.csv',
    'hard_filter_table.csv',
    'exclusion_reason_table.csv',
    'dd_evidence_table.csv',
    'er_brb_scoring_table.csv',
    'risk_matrix.csv',
    'financial_calculation_sheet.csv',
    'claim_to_evidence_map.csv',
    'human_review_checklist.csv',
    'workflow_pce_er_brb_map.csv',
    'certified_research_trace_definition.md',
]

TRACE_FILE_RULES = {
    'candidate_universe_table.csv': {
        'status_labels': ['imported_from_original_bundle', 'pipeline_validated', 'not_reproducible_currently'],
        'current_pipeline_action': 'schema and row-count validation',
        'reproducibility_note': 'Current clean-repo demo does not fully regenerate the candidate universe without the live HK market-data adapter.',
    },
    'hard_filter_table.csv': {
        'status_labels': ['imported_from_original_bundle', 'pipeline_validated', 'needs_human_review'],
        'current_pipeline_action': 'validated and cross-checked by PCE; upstream human_review_required flags are propagated into claim-level and upstream-obligation PCE rows',
        'reproducibility_note': 'Hard-filter logic exists in code/config, but this demo validates the imported table rather than regenerating the original market snapshot.',
    },
    'exclusion_reason_table.csv': {
        'status_labels': ['imported_from_original_bundle', 'pipeline_validated', 'not_reproducible_currently'],
        'current_pipeline_action': 'validated as an imported hard-filter companion artifact',
        'reproducibility_note': 'Not fully regenerated by the current demo pipeline.',
    },
    'dd_evidence_table.csv': {
        'status_labels': ['imported_from_original_bundle', 'pipeline_validated', 'needs_human_review', 'not_reproducible_currently'],
        'current_pipeline_action': 'cross-checked by PCE; needs_review / metadata-only / title-level evidence is downgraded and cannot auto-pass external final delivery',
        'reproducibility_note': 'Document-body parsing is not fully replayed in the current demo pipeline.',
    },
    'er_brb_scoring_table.csv': {
        'status_labels': ['imported_from_original_bundle', 'pipeline_validated', 'needs_human_review'],
        'current_pipeline_action': 'validated and used by PCE to retain evidence gaps, uncertainty labels, and human-review obligations',
        'reproducibility_note': 'Rules and code exist, but the original ER/BRB scoring table is validated rather than fully replayed from raw retrieval inputs.',
    },
    'risk_matrix.csv': {
        'status_labels': ['imported_from_original_bundle', 'pipeline_validated', 'needs_human_review', 'not_reproducible_currently'],
        'current_pipeline_action': 'cross-checked by PCE; unresolved / unknown / human-review risks remain visible as internal-trace or human-review obligations',
        'reproducibility_note': 'Not fully regenerated in the current demo pipeline.',
    },
    'financial_calculation_sheet.csv': {
        'status_labels': ['imported_from_original_bundle', 'pipeline_validated', 'not_reproducible_currently'],
        'current_pipeline_action': 'supported deterministic calculations are replayed; unsupported rows remain imported and validated only',
        'reproducibility_note': 'Only supported deterministic calculations are replayed by the current pipeline.',
    },
    'claim_to_evidence_map.csv': {
        'status_labels': ['imported_from_original_bundle', 'pipeline_validated', 'needs_human_review'],
        'current_pipeline_action': 'imported claim ledger is re-scored by PCE; certification_status and human_review_required are rewritten from upstream cross-check logic',
        'reproducibility_note': 'Claim ledger structure is imported; certification fields are generated by the current pipeline.',
    },
    'human_review_checklist.csv': {
        'status_labels': ['imported_from_original_bundle', 'pipeline_validated', 'needs_human_review', 'not_reproducible_currently'],
        'current_pipeline_action': 'validated as empty/placeholder; current pipeline uses PCE obligation rows instead of claiming this checklist is fully generated',
        'reproducibility_note': 'A future workflow should generate this checklist directly from blockers and review obligations.',
    },
    'workflow_pce_er_brb_map.csv': {
        'status_labels': ['imported_from_original_bundle', 'pipeline_validated'],
        'current_pipeline_action': 'validated as workflow mapping/reference artifact',
        'reproducibility_note': 'Configuration/documentation artifact.',
    },
    'certified_research_trace_definition.md': {
        'status_labels': ['pipeline_validated'],
        'current_pipeline_action': 'required trace definition document checked for presence',
        'reproducibility_note': 'Repository documentation artifact.',
    },
}

DERIVED_OUTPUT_RULES = {
    'pce_audit/pce_audit_current_run.csv': {
        'status_labels': ['pipeline_generated'],
        'current_pipeline_action': 'generated from claim_to_evidence_map plus upstream hard-filter / ER-BRB / DD / risk obligation cross-check',
    },
    'pce_audit/certification_result.json': {
        'status_labels': ['pipeline_generated'],
        'current_pipeline_action': 'generated from PCE cross-check and delivery gate result',
    },
    'delivery/final_delivery_certificate.md': {
        'status_labels': ['pipeline_generated'],
        'current_pipeline_action': 'generated from PCE certification result',
    },
    'delivery/readiness_result.json': {
        'status_labels': ['pipeline_generated'],
        'current_pipeline_action': 'generated from PCE certification result and delivery gate blockers',
    },
    'delivery/final_delivery_gate.md': {
        'status_labels': ['pipeline_generated'],
        'current_pipeline_action': 'generated from explicit delivery-claim reference checks',
    },
}


def count_csv(path: Path) -> int:
    if not path.exists():
        return 0
    with path.open(encoding='utf-8-sig', newline='') as f:
        reader = csv.reader(f)
        try:
            next(reader)
        except StopIteration:
            return 0
        return sum(1 for _ in reader)


def build_trace_manifest(example_dir: Path) -> dict:
    trace_dir = example_dir / 'trace'
    files: dict[str, dict] = {}
    status_index: dict[str, list[str]] = {
        'pipeline_generated': [],
        'pipeline_validated': [],
        'imported_from_original_bundle': [],
        'not_reproducible_currently': [],
        'needs_human_review': [],
    }

    for name in REQUIRED_TRACE:
        path = trace_dir / name
        rule = TRACE_FILE_RULES.get(
            name,
            {
                'status_labels': ['pipeline_validated'],
                'current_pipeline_action': 'presence validation',
                'reproducibility_note': 'No specific provenance rule recorded.',
            },
        )
        row_count = count_csv(path) if name.endswith('.csv') and path.exists() else None
        files[name] = {
            'path': f'trace/{name}',
            'exists': path.exists(),
            'row_count': row_count,
            'status_labels': rule['status_labels'],
            'current_pipeline_action': rule['current_pipeline_action'],
            'reproducibility_note': rule['reproducibility_note'],
        }
        for label in rule['status_labels']:
            status_index.setdefault(label, []).append(name)

    return {
        'generated_at': datetime.now(timezone.utc).isoformat(timespec='seconds'),
        'trace_files': files,
        'status_index': {k: sorted(v) for k, v in status_index.items() if v},
    }


def validate_trace(example_dir: Path) -> dict:
    trace = example_dir / 'trace'
    missing = [name for name in REQUIRED_TRACE if not (trace / name).exists()]
    counts = {
        name: count_csv(trace / name)
        for name in REQUIRED_TRACE
        if name.endswith('.csv') and (trace / name).exists()
    }
    trace_manifest = build_trace_manifest(example_dir)
    return {
        'missing': missing,
        'row_counts': counts,
        'trace_manifest': trace_manifest,
        'pipeline_generated_artifacts': sorted(trace_manifest['status_index'].get('pipeline_generated', [])),
        'pipeline_validated_artifacts': sorted(trace_manifest['status_index'].get('pipeline_validated', [])),
        'imported_from_original_bundle_artifacts': sorted(trace_manifest['status_index'].get('imported_from_original_bundle', [])),
        'not_reproducible_currently_artifacts': sorted(trace_manifest['status_index'].get('not_reproducible_currently', [])),
        'needs_human_review_artifacts': sorted(trace_manifest['status_index'].get('needs_human_review', [])),
    }


def write_final_delivery_gate(example_dir: Path, cert: dict, finished: str) -> None:
    gate = cert.get('delivery_gate', {})
    path = example_dir / 'delivery' / 'final_delivery_gate.md'
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '# Final Delivery Gate',
        '',
        f'- Generated at: {finished}',
        f"- Final delivery allowed: `{bool(cert.get('final_delivery_allowed'))}`",
        f"- Certification status: `{cert.get('certification_status')}`",
        f"- Referenced claim count: {gate.get('referenced_claim_count', 0)}",
        '',
        '## Gate Rule',
        '',
        'Final delivery may cite only material claims that are explicitly referenced as `CLM-*`, present in both `claim_to_evidence_map.csv` and the PCE audit, and certified as `Certified` or `Certified with Caveat` for `external_final` delivery scope.',
        '',
        '## Referenced Claims',
    ]
    refs = gate.get('referenced_claim_ids', [])
    lines.extend(['- None'] if not refs else [f'- {claim_id}' for claim_id in refs[:100]])
    lines.extend(['', '## Blockers'])
    blockers = gate.get('blockers', [])
    lines.extend(['- None'] if not blockers else [f'- {item}' for item in blockers])
    lines.extend(['', '## Warnings'])
    warnings = gate.get('warnings', [])
    lines.extend(['- None'] if not warnings else [f'- {item}' for item in warnings])
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def run_tuntun_hk_demo(repo_root: Path) -> dict:
    ctx = RunContext.for_example(repo_root, 'tuntun_hk')
    run_dir = ctx.example_dir / 'run_records' / ctx.run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    validation = validate_trace(ctx.example_dir)
    replay = replay_trace_calculations(ctx.example_dir)
    cert = certify_example(ctx.example_dir)
    finished = datetime.now(timezone.utc).isoformat(timespec='seconds')

    trace_manifest = validation['trace_manifest']
    pce_summary = {
        'generated_at': finished,
        'certification_status': cert.get('certification_status'),
        'final_delivery_allowed': bool(cert.get('final_delivery_allowed')),
        'status_counts': cert.get('status_counts', {}),
        'scope_status_counts': cert.get('scope_status_counts', {}),
        'human_review_required_count': cert.get('human_review_required_count', 0),
        'external_final_blocked_count': cert.get('external_final_blocked_count', 0),
        'external_final_caveated_count': cert.get('external_final_caveated_count', 0),
        'blockers': cert.get('blockers', []),
        'warnings': cert.get('warnings', []),
        'pce_cross_check': cert.get('pce_cross_check', {}),
    }
    delivery_gate_summary = {
        'generated_at': finished,
        'certification_status': cert.get('certification_status'),
        'final_delivery_allowed': bool(cert.get('final_delivery_allowed')),
        'delivery_gate': cert.get('delivery_gate', {}),
        'blockers': cert.get('blockers', []),
        'warnings': cert.get('warnings', []),
    }

    summary = {
        'run_id': ctx.run_id,
        'started_at': ctx.started_at,
        'finished_at': finished,
        'command': 'python scripts/run_tuntun_hk_demo.py',
        'config': str(ctx.config_path.relative_to(repo_root)),
        'input': 'examples/tuntun_hk/input/',
        'trace': 'examples/tuntun_hk/trace/',
        'pce_audit': 'examples/tuntun_hk/pce_audit/',
        'delivery': 'examples/tuntun_hk/delivery/',
        'trace_validation': validation,
        'calculation_replay': replay,
        'pce_certification': cert,
        'run_record_artifacts': {
            'run_summary_json': f'examples/tuntun_hk/run_records/{ctx.run_id}/run_summary.json',
            'trace_manifest_json': f'examples/tuntun_hk/run_records/{ctx.run_id}/trace_manifest.json',
            'pce_summary_json': f'examples/tuntun_hk/run_records/{ctx.run_id}/pce_summary.json',
            'delivery_gate_summary_json': f'examples/tuntun_hk/run_records/{ctx.run_id}/delivery_gate_summary.json',
            'warnings_md': f'examples/tuntun_hk/run_records/{ctx.run_id}/warnings.md',
        },
        'caveat': (
            'Current demo validates imported trace artifacts, replays supported calculations, regenerates PCE audit/certification/readiness, '
            'and blocks final delivery when material delivery claims are not explicitly mapped to certified PCE rows. Full live market-data regeneration is not claimed.'
        ),
    }

    (run_dir / 'run_record.json').write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding='utf-8')
    (run_dir / 'run_summary.json').write_text(
        json.dumps(
            {
                'run_id': ctx.run_id,
                'started_at': ctx.started_at,
                'finished_at': finished,
                'command': 'python scripts/run_tuntun_hk_demo.py',
                'config': str(ctx.config_path.relative_to(repo_root)),
                'input': 'examples/tuntun_hk/input/',
                'trace': 'examples/tuntun_hk/trace/',
                'calculation_replay': replay,
                'trace_missing_files': validation['missing'],
                'pipeline_generated_artifacts': validation['pipeline_generated_artifacts'],
                'pipeline_validated_artifacts': validation['pipeline_validated_artifacts'],
                'imported_from_original_bundle_artifacts': validation['imported_from_original_bundle_artifacts'],
                'not_reproducible_currently_artifacts': validation['not_reproducible_currently_artifacts'],
                'needs_human_review_artifacts': validation['needs_human_review_artifacts'],
                'certification_status': cert.get('certification_status'),
                'final_delivery_allowed': bool(cert.get('final_delivery_allowed')),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding='utf-8',
    )
    (run_dir / 'trace_manifest.json').write_text(json.dumps(trace_manifest, ensure_ascii=False, indent=2), encoding='utf-8')
    (run_dir / 'pce_summary.json').write_text(json.dumps(pce_summary, ensure_ascii=False, indent=2), encoding='utf-8')
    (run_dir / 'delivery_gate_summary.json').write_text(json.dumps(delivery_gate_summary, ensure_ascii=False, indent=2), encoding='utf-8')

    warnings_lines = [
        '# Warnings and Caveats',
        '',
        '## Delivery Decision',
        '',
        f"- certification_status: `{cert.get('certification_status')}`",
        f"- final_delivery_allowed: `{bool(cert.get('final_delivery_allowed'))}`",
        '',
        '## Blockers',
    ]
    blockers = cert.get('blockers', [])
    warnings_lines.extend(['- None'] if not blockers else [f'- {item}' for item in blockers])
    warnings_lines.extend(['', '## Warnings'])
    warnings = cert.get('warnings', [])
    warnings_lines.extend(['- None'] if not warnings else [f'- {item}' for item in warnings])
    warnings_lines.extend(['', '## Trace Provenance Flags'])
    for label in ['pipeline_validated', 'imported_from_original_bundle', 'not_reproducible_currently', 'needs_human_review']:
        items = trace_manifest['status_index'].get(label, [])
        warnings_lines.append(f"- {label}: {', '.join(items) if items else 'None'}")
    (run_dir / 'warnings.md').write_text('\n'.join(warnings_lines) + '\n', encoding='utf-8')

    lines = [
        '# Run Summary',
        '',
        f'- Run ID: `{ctx.run_id}`',
        f'- Started: {ctx.started_at}',
        f'- Finished: {finished}',
        '- Command: `python scripts/run_tuntun_hk_demo.py`',
        f'- Trace missing files: {validation["missing"] or "None"}',
        f'- Calculation replayed claims: {replay.get("replayed_claim_count", 0)}',
        f'- PCE status: `{cert.get("certification_status")}`',
        f'- Final delivery allowed: `{cert.get("final_delivery_allowed")}`',
        '',
        '## Run Record Files',
        '',
        f'- `examples/tuntun_hk/run_records/{ctx.run_id}/run_summary.json`',
        f'- `examples/tuntun_hk/run_records/{ctx.run_id}/trace_manifest.json`',
        f'- `examples/tuntun_hk/run_records/{ctx.run_id}/pce_summary.json`',
        f'- `examples/tuntun_hk/run_records/{ctx.run_id}/delivery_gate_summary.json`',
        f'- `examples/tuntun_hk/run_records/{ctx.run_id}/warnings.md`',
        '',
        '## Caveat',
        '',
        'Current demo validates imported trace artifacts, replays supported calculations, regenerates PCE audit/certification/readiness, and blocks final delivery when material delivery claims are not explicitly mapped to certified PCE rows. Full live market-data replay requires live data-source access.',
    ]
    (run_dir / 'run_summary.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')

    readiness = {
        'ready': bool(cert.get('final_delivery_allowed')),
        'certification_status': cert.get('certification_status'),
        'checked_at': finished,
        'blockers': cert.get('blockers', []),
        'warnings': cert.get('warnings', []),
        'delivery_gate': cert.get('delivery_gate', {}),
    }
    (ctx.example_dir / 'delivery/readiness_result.json').write_text(
        json.dumps(readiness, ensure_ascii=False, indent=2),
        encoding='utf-8',
    )
    write_final_delivery_gate(ctx.example_dir, cert, finished)
    (ctx.example_dir / 'delivery/delivery_manifest.json').write_text(
        json.dumps(
            {
                'generated_at': finished,
                'project': 'certified-shell-company-screening-agent',
                'case': 'tuntun_hk',
                'status': {
                    'readiness': 'READY' if cert.get('final_delivery_allowed') else 'BLOCKED',
                    'certificate_status': cert.get('certification_status'),
                    'final_delivery_allowed': bool(cert.get('final_delivery_allowed')),
                    'status_counts': cert.get('status_counts', {}),
                    'scope_status_counts': cert.get('scope_status_counts', {}),
                    'human_review_required_count': cert.get('human_review_required_count', 0),
                    'delivery_gate': cert.get('delivery_gate', {}),
                    'blockers': cert.get('blockers', []),
                    'warnings': cert.get('warnings', []),
                },
                'trace_manifest': trace_manifest,
                'derived_outputs': DERIVED_OUTPUT_RULES,
                'files': [
                    {'path': 'pce_audit/pce_audit_current_run.csv', 'role': 'pipeline-generated PCE audit'},
                    {'path': 'pce_audit/certification_result.json', 'role': 'pipeline-generated certification result'},
                    {'path': 'delivery/final_delivery_certificate.md', 'role': 'pipeline-generated delivery certificate'},
                    {'path': 'delivery/final_delivery_gate.md', 'role': 'pipeline-generated delivery gate summary'},
                    {'path': 'delivery/readiness_result.json', 'role': 'pipeline-generated readiness result'},
                    {'path': 'trace/claim_to_evidence_map.csv', 'role': 'imported claim ledger with pipeline-refreshed PCE status fields'},
                ],
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding='utf-8',
    )
    return summary
